### ISSUE TITLE
How do I launch it?

### ISSUE THREAD

**Issue by ElonMuskIdiot** [unfuncaptcha/bda#2]
How do I launch it?

**Comment by spearphishing** [comment]
To install the package, run:

```
$ python -m pip install unfuncaptcha-bda
```

Now you can import and use the package like so:

```py
from unfuncaptcha_bda import ArkoseBrowserFingerprint

# define bda, user_agent, and timestamp before instantiation
fp = ArkoseBrowserFingerprint(bda, user_agent, timestamp)

**Comment by ElonMuskIdiot** [comment]
I understand how to install it, but I don't understand how to run it normally, I tried to run it on python itself and in Visual studio. In the end, I received nothing in the response, only the pycache folder was created, but there is something incomprehensible in it. Can I read the launch instructions in more detail please
