### ISSUE TITLE
How do i launch it?

### ISSUE THREAD

**Issue by ElonMuskIdiot** [unfuncaptcha/bda#3]
I understand how to install it, but I don't understand how to run it normally, I tried to run it on python itself and in Visual studio. In the end, I received nothing in the response, only the pycache folder was created, but there is something incomprehensible in it. Can I read the launch instructions in more detail please

**Comment by ElonMuskIdiot** [comment]
And please tell me what exactly does this script generate? Only BDA ?

**Comment by spearphishing** [comment]
This script does **not** generate BDA's, it allows you to load, edit, and repackage a given BDA.

At some point I will publish a fully features library that allows for BDA generation, token fetching, solving, etc. But for now there's this.

Also when you are trying to use the library, what code are you running? If you could send the snippet you're having trouble with I may be able to help you.

**Comment by ElonMuskIdiot** [comment]
Yes, in principle, none of these codes gives me any answer in response, what data should I enter in order for this code to work?

**Comment by spearphishing** [comment]
Do you have a BDA you are trying to operate on?

**Comment by ElonMuskIdiot** [comment]
Yes, I have a bda, or you can write to me in tg @toptraffic777. It is not very convenient to communicate here
