### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by standfv** [unfuncaptcha/bda#5]
![image](https://github.com/user-attachments/assets/f90d7e0b-0242-47d3-ae4f-ed0ab075b3b2)

**Comment by standfv** [comment]
help me...

**Comment by phaeton1199** [comment]
`pip install pycryptodome`

This should solve your issue.

**Comment by standfv** [comment]
> `pip install pycryptodome`
> 
> This should solve your issue.

thanks
